import { FormBuilder, Validators } from '@angular/forms';

export function getRecurrentTaskModel(formValue: any) {
  if (formValue.id == null) formValue.id = 0;
  let task = { ...formValue };
  return task;
}

// const userId = localStorage.getItem('userId');
// const userName = localStorage.getItem('userName');

export function buildForm(formbuilder: FormBuilder) {
  return formbuilder.group({
    id: 0,
    title: [],
    taskTypeId: [],
    taskType: [],
    frequesntId: ['', Validators.required],
    frequesnt: [],
    firstDate: [],
    secondDate: [],
    renewed: false,
    statusId: [],
    status: [],
    date: new Date(),
    startDate: [],
    endDate: [],
    dateView: [],
    startDateView: [],
    endDateView: [],
    workingHours: 0,
    siteId: [],
    siteName: [],
    engineerUser1Id: [],
    engineerUser2Id: [],
    engineerUser1Name: [],
    engineerUser2Name: [],
    sunday:false,
    monday:false,
    tuesday:false,
    wednesday:false,
    thursday:false,
    friday:false,
    saturday:false,
    taskStatusId: [],
    taskStatusName: [],
    comment: [],
    // Room fields
    roomId: [],
    roomName: [],

    roomTemperature: true,
    roomHumidity: true,
    valvesStatus: true,
    alarmsCheck: true,
    leakageCheck: true,
    o2ManifoldMainOut: true,
    o2ManifoldRightBank: true,
    o2ManifoldLeftBank: true,
    o2ManifoldEmergency: true,
    n2OMainout: true,
    n2ORightBank: true,
    n2OLeftBank: true,
    n2OEmergencyBank: true,
    medicalAirMainOut: true,
    medicalAirRightBank: true,
    medicalAirLeftBank: true,
    medicalAirEmergencyBank: true,
    cO2MainOut: true,
    cO2RightBank: true,
    cO2LeftBank: true,
    cO2EmergencyBank: true,
    n2MainOut: true,
    n2RightBank: true,
    n2LeftBank: true,
    n2EmergencyBank: true,
    loX1Volume: [],
    loX2Volume: [],
    loX1Pressure: true,
    loX2Pressure: true,
    compressorsCheckforAnyUnusualNoise: true,
    compressorsOutputPressure: true,
    compressorsMedicalAirLinePressure7To8Bar: true,
    compressorsMedicalAirLinePressure4To5Bar: true,
    dryersCheckforAlarmOrUnusualNoise: true,
    vacuumPumpCheckOilLeakage: true,
    vacuumPumpCheckForAnyUnusualNoise: true,
    vacuumPumpPressure: true,
    agssCheckForAnyAlarm: true,
    agssCheckManualOperation: true,
    agssCheckAndCleanFilter: true,
    o2KTypeEmpty: [],
    o2MTypeEmpty: [],
    o2ETypeEmpty: [],
    o2DTypeEmpty: [],
    makTypeEmpty: [],
    maeTypeEmpty: [],
    n2OKTypeEmpty: 0,
    n2OETypeEmpty: [],
    cO2KTypeEmpty: [],
    cO2ETypeEmpty: [],
    mixtureMTypeEmpty: [],
    n2KTypeEmpty: [],
    pftMixEmpty: [],
    pftHeliumEmpty: [],
    liquidNitrogenLarge121LEmpty: [],
    liquidNitrogenMedium50LEmpty: [],
    liquidNitrogenSmall30LEmpty: [],
    nitricoxidE11PPM: [],
    nitricoxidE25PPM: [],
    // For search
    parentId: [],
    isChild: [],
  });
}
